(cl:defpackage vitarana_drone-msg
  (:use )
  (:export
   "<DETECTIONFEATURES>"
   "DETECTIONFEATURES"
   "<IMAGEFEATURES>"
   "IMAGEFEATURES"
   "<TARGETGPSPOSITION>"
   "TARGETGPSPOSITION"
   "<TARGETPOSITION>"
   "TARGETPOSITION"
   "<EDRONE_CMD>"
   "EDRONE_CMD"
   "<PROP_SPEED>"
   "PROP_SPEED"
  ))

