// Generated by gencpp from file vitarana_drone/TargetGpsPosition.msg
// DO NOT EDIT!


#ifndef VITARANA_DRONE_MESSAGE_TARGETGPSPOSITION_H
#define VITARANA_DRONE_MESSAGE_TARGETGPSPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vitarana_drone
{
template <class ContainerAllocator>
struct TargetGpsPosition_
{
  typedef TargetGpsPosition_<ContainerAllocator> Type;

  TargetGpsPosition_()
    : longitude(0.0)
    , latitude(0.0)  {
    }
  TargetGpsPosition_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)  {
  (void)_alloc;
    }



   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _latitude_type;
  _latitude_type latitude;





  typedef boost::shared_ptr< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> const> ConstPtr;

}; // struct TargetGpsPosition_

typedef ::vitarana_drone::TargetGpsPosition_<std::allocator<void> > TargetGpsPosition;

typedef boost::shared_ptr< ::vitarana_drone::TargetGpsPosition > TargetGpsPositionPtr;
typedef boost::shared_ptr< ::vitarana_drone::TargetGpsPosition const> TargetGpsPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator1> & lhs, const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator2> & rhs)
{
  return lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator1> & lhs, const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vitarana_drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "826f8fcadfa8742a6495798d3978624a";
  }

  static const char* value(const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x826f8fcadfa8742aULL;
  static const uint64_t static_value2 = 0x6495798d3978624aULL;
};

template<class ContainerAllocator>
struct DataType< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vitarana_drone/TargetGpsPosition";
  }

  static const char* value(const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 longitude\n"
"float32 latitude\n"
;
  }

  static const char* value(const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetGpsPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vitarana_drone::TargetGpsPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vitarana_drone::TargetGpsPosition_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VITARANA_DRONE_MESSAGE_TARGETGPSPOSITION_H
